logging:
  level:
    jdbc:
      sqltiming: info
      resultsettable: info
      sqlonly: fatal
      audit: fatal
      resultset: fatal
      connection: fatal
    org:
      springframework:
        web: debug
        orm: debug
    greyhound: debug

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim:
    sql:
      extrablanklines: false
