logging:
  level:
    jdbc:
      sqltiming: info
      resultsettable: info
      sqlonly: fatal
      audit: fatal
      resultset: fatal
      connection: fatal
#    org:
#      springframework:
#        web: debug
#        orm: debug
    greyhound: debug

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim:
    sql:
      extrablanklines: false

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          fetch_size: 100
          batch_versioned_data: true
    hibernate:
      ddl-auto: create-drop